trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: ni (2)
      name: ni/niveristand-custom-device-build-tools
# TEMPORARY, include fake custom device to use templates until migrating the templates into build tools makes sense
    - repository: imitation-cd
      type: github
      ref: main
      endpoint: papowerNI
      name: papowerNI/imitation-cd

  pipelines:
    - pipeline: VeristandMessageLibrary
      source:   ni.niveristand-custom-device-message-library
      trigger:  true

pool:
  name: custom-device-temp # TEMPORARY, eventually use an official build pool of custom device agents
  demands:
    - agent.os -equals Windows_NT

# --------- Build Parameters here ---------
parameters:
    # customDeviceRepoName - Name of the Custom Device Repository on GitHub
  - name:    customDeviceRepoName
    type:    string
    default:  niveristand-routing-and-faulting-message-library

    # lvVersions - each LabVIEW version, bitness, and release nomenclature combination to build
  - name:    lvVersions
    type:    object
    default:
      - version: '2020'
        bitness: '32-bit'
      - version: '2021'
        bitness: '64-bit'
      # - version: '2023' TEMPORARY, disable 2023 build since LabVIEW is still buggy
      #   bitness: '64-bit'

    # dependencies - source location, file, and copy destination
  - name:    dependencies
    type:    object
    default: 
      - source: '\\nirvana\temp\papower\Measurements\VeriStandAddons\messaging_library'
        file: 'CDMessaging.lvlibp'
        destination: 'Includes'

    # buildSteps - list of each project, buildOperation, target, and buildSpec combination to build 
    # Note: target and buildSpec may be empty for some buildOperations
  - name:    buildSteps
    type:    object
    default:
      - projectLocation: 'Source\SLSC Switch\SLSC Switch Messaging.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'SLSC Switch Messaging'

      - projectLocation: 'Source\SLSC Switch\SLSC Switch Messaging.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'Linux x64'
        buildSpec: 'SLSC Switch Messaging'

      - projectLocation: 'Source\NI-SWITCH\NI-SWITCH Messaging.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'NI-SWITCH Messaging'

      - projectLocation: 'Source\NI-SWITCH\NI-SWITCH Messaging.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'Linux x64'
        buildSpec: 'NI-SWITCH Messaging'

    # buildOutputLocation - location where LV build outputs are stored
  - name:    buildOutputLocation
    type:    string
    default: 'Source\Built'

    # packages - configuration for each nipkg to build
  - name:    packages
    type:    object
    default:
      - noPackage: ''

    # archiveLocation - location to store build artifacts for archival
  - name:    archiveLocation
    type:    string
    default: '\\nirvana\temp\papower\Measurements\VeriStandAddons\slsc_switch_messaging_library'

# --------- Call Build Templates ---------
# Note: If custom build steps are needed for a particular custom device, they can be inserted before or after existing templates below
# TEMPORARY, point template locations to imitation-cd instead of build-tools while in development
stages:
  - stage: build
    jobs:
      - ${{ each lvVersion in parameters.lvVersions }}:
        - job:
          displayName: Build ${{ parameters.customDeviceRepoName }} for LabVIEW ${{ lvVersion.version }}
          steps:
            - template: azure-templates\pre-job-steps.yml@imitation-cd # Configure variables, check out repos, Clear cache
              parameters:
                customDeviceRepoName:  ${{ parameters.customDeviceRepoName }}
                lvVersion:             ${{ lvVersion.version }}
                bitness:               ${{ lvVersion.bitness }} 

            - ${{ each buildStep in parameters.buildSteps }}:
              - template: azure-templates\build-op-steps.yml@imitation-cd # config file and build specs
                parameters:
                  projectLocation: ${{ buildStep.projectLocation }}
                  buildOperation:  ${{ buildStep.buildOperation }}
                  target:          ${{ buildStep.target }}
                  buildSpec:       ${{ buildStep.buildSpec }}
                  dependencies:    ${{ parameters.dependencies }}

            - template: azure-templates\post-job-steps.yml@imitation-cd # nipkg and archive
              parameters:
                packages:            ${{ parameters.packages }}
                buildOutputLocation: ${{ parameters.buildOutputLocation }}
                archiveLocation:     ${{ parameters.archiveLocation }}
                pack:                false