[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\slsc_switch_messaging_library'

[dependencies.niveristand-custom-device-message-library]
libraries = ['CDMessaging.lvlibp']
copy_location = 'Includes'

[projects.slsc_switch]
path = 'Source\SLSC Switch\SLSC Switch Messaging.lvproj'

[projects.ni_switch]
path = 'Source\NI-SWITCH\NI-SWITCH Messaging.lvproj'

[[build.steps]]
name = 'Windows SLSC Switch Library'
type = 'lvBuildSpec'
project = '{slsc_switch}'
target = 'My Computer'
build_spec = 'SLSC Switch Messaging'
dependency_target = 'Windows'

[[build.steps]]
name = 'Linux x64 SLSC Switch Library'
type = 'lvBuildSpec'
project = '{slsc_switch}'
target = 'Linux x64'
build_spec = 'SLSC Switch Messaging'
dependency_target = 'Linux_x64'

[[build.steps]]
name = 'Windows NI-SWITCH Library'
type = 'lvBuildSpec'
project = '{ni_switch}'
target = 'My Computer'
build_spec = 'NI-SWITCH Messaging'
dependency_target = 'Windows'

[[build.steps]]
name = 'Linux x64 NI-SWITCH Library'
type = 'lvBuildSpec'
project = '{ni_switch}'
target = 'Linux x64'
build_spec = 'NI-SWITCH Messaging'
dependency_target = 'Linux_x64'

[notification]
type = 'teams'
